/****************************************************************************
 * arch/arm/src/stm32n6/hardware/stm32n6xxx_pinmap.h
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

#ifndef __ARCH_ARM_SRC_STM32N6_HARDWARE_STM32N6XXX_PINMAP_H
#define __ARCH_ARM_SRC_STM32N6_HARDWARE_STM32N6XXX_PINMAP_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Alternate Pin Functions.
 *
 * Alternative pin selections are provided with a numeric suffix like _1, _2,
 * etc.  Drivers, however, will use the pin selection without the numeric
 * suffix.  Additional definitions are required in the board.h file.  For
 * example, if USART1_TX connects via PE5 on some board, then the following
 * definition should appear in the board.h header file for that board:
 *
 * #define GPIO_USART1_TX GPIO_USART1_TX_1
 *
 * The driver will then automatically configure PE5 as the USART1 TX pin.
 */

/* USART1: PE5=TX (AF7), PE6=RX (AF7) - ST-Link Virtual COM Port */

#define GPIO_USART1_TX_1   (GPIO_ALT | GPIO_AF7 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTE | GPIO_PIN5)
#define GPIO_USART1_RX_1   (GPIO_ALT | GPIO_AF7 | GPIO_SPEED_50MHZ | GPIO_PORTE | GPIO_PIN6)

/* USART2: PD5=TX (AF7), PD6=RX (AF7) */

#define GPIO_USART2_TX_1   (GPIO_ALT | GPIO_AF7 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTD | GPIO_PIN5)
#define GPIO_USART2_RX_1   (GPIO_ALT | GPIO_AF7 | GPIO_SPEED_50MHZ | GPIO_PORTD | GPIO_PIN6)

/* USART3: PD8=TX (AF7), PD9=RX (AF7) */

#define GPIO_USART3_TX_1   (GPIO_ALT | GPIO_AF7 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTD | GPIO_PIN8)
#define GPIO_USART3_RX_1   (GPIO_ALT | GPIO_AF7 | GPIO_SPEED_50MHZ | GPIO_PORTD | GPIO_PIN9)

/* SPI1 (AF5): PA4=NSS, PA5=SCK, PA6=MISO, PA7=MOSI
 *             PB3=SCK, PB4=MISO, PB5=MOSI (alternate set)
 */

#define GPIO_SPI1_NSS_1    (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN4)
#define GPIO_SPI1_SCK_1    (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN5)
#define GPIO_SPI1_MISO_1   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PORTA | GPIO_PIN6)
#define GPIO_SPI1_MOSI_1   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN7)
#define GPIO_SPI1_SCK_2    (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN3)
#define GPIO_SPI1_MISO_2   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PORTB | GPIO_PIN4)
#define GPIO_SPI1_MOSI_2   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN5)

/* SPI2 (AF5): PB10=SCK, PB14=MISO, PB15=MOSI, PB12=NSS
 *             PB9=NSS, PC2=MISO, PC3=MOSI (alternate)
 */

#define GPIO_SPI2_NSS_1    (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN12)
#define GPIO_SPI2_SCK_1    (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN10)
#define GPIO_SPI2_MISO_1   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PORTB | GPIO_PIN14)
#define GPIO_SPI2_MOSI_1   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN15)
#define GPIO_SPI2_NSS_2    (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN9)
#define GPIO_SPI2_MISO_2   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PORTC | GPIO_PIN2)
#define GPIO_SPI2_MOSI_2   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN3)

/* SPI3 (AF6): PB3=SCK, PB4=MISO, PB5=MOSI, PA15=NSS
 *             PC10=SCK, PC11=MISO, PC12=MOSI (alternate)
 */

#define GPIO_SPI3_NSS_1    (GPIO_ALT | GPIO_AF6 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN15)
#define GPIO_SPI3_SCK_1    (GPIO_ALT | GPIO_AF6 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN3)
#define GPIO_SPI3_MISO_1   (GPIO_ALT | GPIO_AF6 | GPIO_SPEED_100MHZ | GPIO_PORTB | GPIO_PIN4)
#define GPIO_SPI3_MOSI_1   (GPIO_ALT | GPIO_AF6 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN5)
#define GPIO_SPI3_SCK_2    (GPIO_ALT | GPIO_AF6 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN10)
#define GPIO_SPI3_MISO_2   (GPIO_ALT | GPIO_AF6 | GPIO_SPEED_100MHZ | GPIO_PORTC | GPIO_PIN11)
#define GPIO_SPI3_MOSI_2   (GPIO_ALT | GPIO_AF6 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN12)

/* SPI4 (AF5): PE2=SCK, PE5=MISO, PE6=MOSI, PE4=NSS */

#define GPIO_SPI4_NSS_1    (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTE | GPIO_PIN4)
#define GPIO_SPI4_SCK_1    (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTE | GPIO_PIN2)
#define GPIO_SPI4_MISO_1   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PORTE | GPIO_PIN5)
#define GPIO_SPI4_MOSI_1   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTE | GPIO_PIN6)

/* SPI5 (AF5): PF15=SCK, PF12=MISO, PF11=MOSI */

#define GPIO_SPI5_SCK_1    (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTF | GPIO_PIN15)
#define GPIO_SPI5_MISO_1   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PORTF | GPIO_PIN12)
#define GPIO_SPI5_MOSI_1   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTF | GPIO_PIN11)

/* SPI5 (AF5): PE15=SCK, PG1=MISO, PG2=MOSI — Nucleo Arduino/morpho header */

#define GPIO_SPI5_SCK_2    (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTE | GPIO_PIN15)
#define GPIO_SPI5_MISO_2   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PORTG | GPIO_PIN1)
#define GPIO_SPI5_MOSI_2   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTG | GPIO_PIN2)

/* SPI6 (AF5): PA5=SCK, PA6=MISO, PA7=MOSI, PA4=NSS (shared with SPI1) */

#define GPIO_SPI6_NSS_1    (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN4)
#define GPIO_SPI6_SCK_1    (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN5)
#define GPIO_SPI6_MISO_1   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PORTA | GPIO_PIN6)
#define GPIO_SPI6_MOSI_1   (GPIO_ALT | GPIO_AF5 | GPIO_SPEED_100MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN7)

/* I2C1 (AF4): PE5=SCL, PE6=SDA — shared with USART1, not usable simultaneously */

#define GPIO_I2C1_SCL_1    (GPIO_ALT | GPIO_AF4 | GPIO_SPEED_50MHZ | GPIO_OPENDRAIN | GPIO_PORTE | GPIO_PIN5)
#define GPIO_I2C1_SDA_1    (GPIO_ALT | GPIO_AF4 | GPIO_SPEED_50MHZ | GPIO_OPENDRAIN | GPIO_PORTE | GPIO_PIN6)

/* I2C1 (AF4): PH9=SCL, PC1=SDA — Nucleo Arduino D15/D14 (with SB mod) or morpho CN15 */

#define GPIO_I2C1_SCL_2    (GPIO_ALT | GPIO_AF4 | GPIO_SPEED_50MHZ | GPIO_OPENDRAIN | GPIO_PORTH | GPIO_PIN9)
#define GPIO_I2C1_SDA_2    (GPIO_ALT | GPIO_AF4 | GPIO_SPEED_50MHZ | GPIO_OPENDRAIN | GPIO_PORTC | GPIO_PIN1)

/* I2C2 (AF4): PB10=SCL, PB11=SDA — TCPP0203 USB Type-C controller */

#define GPIO_I2C2_SCL_1    (GPIO_ALT | GPIO_AF4 | GPIO_SPEED_50MHZ | GPIO_OPENDRAIN | GPIO_PORTB | GPIO_PIN10)
#define GPIO_I2C2_SDA_1    (GPIO_ALT | GPIO_AF4 | GPIO_SPEED_50MHZ | GPIO_OPENDRAIN | GPIO_PORTB | GPIO_PIN11)

/* I2C3 (AF4): PA8=SCL, PC9=SDA */

#define GPIO_I2C3_SCL_1    (GPIO_ALT | GPIO_AF4 | GPIO_SPEED_50MHZ | GPIO_OPENDRAIN | GPIO_PORTA | GPIO_PIN8)
#define GPIO_I2C3_SDA_1    (GPIO_ALT | GPIO_AF4 | GPIO_SPEED_50MHZ | GPIO_OPENDRAIN | GPIO_PORTC | GPIO_PIN9)

/* I2C4 (AF4): PD12=SCL, PD13=SDA */

#define GPIO_I2C4_SCL_1    (GPIO_ALT | GPIO_AF4 | GPIO_SPEED_50MHZ | GPIO_OPENDRAIN | GPIO_PORTD | GPIO_PIN12)
#define GPIO_I2C4_SDA_1    (GPIO_ALT | GPIO_AF4 | GPIO_SPEED_50MHZ | GPIO_OPENDRAIN | GPIO_PORTD | GPIO_PIN13)

/* Timer PWM Output Pin Definitions ****************************************
 *
 * Timer output pins use GPIO AF mode.  "_OUT" suffix indicates output
 * direction for PWM.  Board.h selects which variant to use.
 */

/* TIM1 (AF1): Advanced timer, 4 channels + complementary */

#define GPIO_TIM1_CH1OUT_1  (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN8)
#define GPIO_TIM1_CH1OUT_2  (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTE | GPIO_PIN9)
#define GPIO_TIM1_CH2OUT_1  (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN9)
#define GPIO_TIM1_CH2OUT_2  (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTE | GPIO_PIN11)
#define GPIO_TIM1_CH3OUT_1  (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN10)
#define GPIO_TIM1_CH3OUT_2  (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTE | GPIO_PIN13)
#define GPIO_TIM1_CH4OUT_1  (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN11)
#define GPIO_TIM1_CH4OUT_2  (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTE | GPIO_PIN14)
#define GPIO_TIM1_CH1NOUT_1 (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN7)
#define GPIO_TIM1_CH1NOUT_2 (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN13)
#define GPIO_TIM1_CH1NOUT_3 (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTE | GPIO_PIN8)
#define GPIO_TIM1_CH2NOUT_1 (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN0)
#define GPIO_TIM1_CH2NOUT_2 (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN14)
#define GPIO_TIM1_CH2NOUT_3 (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTE | GPIO_PIN10)
#define GPIO_TIM1_CH3NOUT_1 (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN1)
#define GPIO_TIM1_CH3NOUT_2 (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN15)
#define GPIO_TIM1_CH3NOUT_3 (GPIO_ALT | GPIO_AF1 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTE | GPIO_PIN12)

/* TIM3 (AF2): General purpose 16-bit, 4 channels */

#define GPIO_TIM3_CH1OUT_1  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN6)
#define GPIO_TIM3_CH1OUT_2  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN4)
#define GPIO_TIM3_CH1OUT_3  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN6)
#define GPIO_TIM3_CH2OUT_1  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN7)
#define GPIO_TIM3_CH2OUT_2  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN5)
#define GPIO_TIM3_CH2OUT_3  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN7)
#define GPIO_TIM3_CH3OUT_1  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN0)
#define GPIO_TIM3_CH3OUT_2  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN8)
#define GPIO_TIM3_CH4OUT_1  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN1)
#define GPIO_TIM3_CH4OUT_2  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN9)

/* TIM4 (AF2): General purpose 16-bit, 4 channels */

#define GPIO_TIM4_CH1OUT_1  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN6)
#define GPIO_TIM4_CH1OUT_2  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTD | GPIO_PIN12)
#define GPIO_TIM4_CH2OUT_1  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN7)
#define GPIO_TIM4_CH2OUT_2  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTD | GPIO_PIN13)
#define GPIO_TIM4_CH3OUT_1  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN8)
#define GPIO_TIM4_CH3OUT_2  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTD | GPIO_PIN14)
#define GPIO_TIM4_CH4OUT_1  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN9)
#define GPIO_TIM4_CH4OUT_2  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTD | GPIO_PIN15)

/* TIM5 (AF2): General purpose 32-bit, 4 channels */

#define GPIO_TIM5_CH1OUT_1  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN0)
#define GPIO_TIM5_CH2OUT_1  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN1)
#define GPIO_TIM5_CH3OUT_1  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN2)
#define GPIO_TIM5_CH4OUT_1  (GPIO_ALT | GPIO_AF2 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN3)

/* TIM8 (AF3): Advanced timer, 4 channels + complementary */

#define GPIO_TIM8_CH1OUT_1  (GPIO_ALT | GPIO_AF3 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN6)
#define GPIO_TIM8_CH2OUT_1  (GPIO_ALT | GPIO_AF3 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN7)
#define GPIO_TIM8_CH3OUT_1  (GPIO_ALT | GPIO_AF3 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN8)
#define GPIO_TIM8_CH4OUT_1  (GPIO_ALT | GPIO_AF3 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN9)
#define GPIO_TIM8_CH1NOUT_1 (GPIO_ALT | GPIO_AF3 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN5)
#define GPIO_TIM8_CH2NOUT_1 (GPIO_ALT | GPIO_AF3 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN0)
#define GPIO_TIM8_CH3NOUT_1 (GPIO_ALT | GPIO_AF3 | GPIO_SPEED_50MHZ | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN1)

/* ADC Analog Pin Definitions **********************************************
 *
 * ADC pins use GPIO analog mode (MODER=11).  No alternate function needed.
 * Channel assignments from STM32N657 datasheet.
 */

#define GPIO_ADC1_INP5     (GPIO_ANALOG | GPIO_PORTF | GPIO_PIN5)   /* A0 */
#define GPIO_ADC1_INP10    (GPIO_ANALOG | GPIO_PORTC | GPIO_PIN10)  /* A1 */
#define GPIO_ADC1_INP11    (GPIO_ANALOG | GPIO_PORTF | GPIO_PIN6)   /* A2 */
#define GPIO_ADC1_INP13    (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN2)   /* A3 */

#endif /* __ARCH_ARM_SRC_STM32N6_HARDWARE_STM32N6XXX_PINMAP_H */
